server:
  port: 7074
spring:
  application:
    name: service-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.ms.com:18761/eureka/
zuul:
  sensitive-headers: Cookie,Set-Cookie,Authorization
  ignoredServices: Cookie,Set-Cookie,Authorization
  routes:
    api-ribbon:
      path: /api-ribbon/**
      serviceId: service-ribbon
    api-feign:
      path: /api-feign/**
      serviceId: service-feign
