server:
  port: 7074
spring:
  application:
    name: service-zuul
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.20.240.9:3306/springcloud
    username: root
    password: UbtSHppzQLKN6XeZ

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.ms.com:18761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

# zuul:
#   sensitive-headers: Cookie,Set-Cookie,Authorization
#   ignoredServices: Cookie,Set-Cookie,Authorization
#   routes:
#     api-ribbon:
#       path: /api-ribbon/**
#       serviceId: service-ribbon
#     api-feign:
#       path: /api-feign/**
#       serviceId: service-feign
