server:
  port: 7075
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/wupengwuhao/springcloud/
          searchPaths: config-respo
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery.springcloudservice.com:7070/eureka/
